Feature/ranking view
GBZG/GBZG pull request #14
Opened 2023-01-18 15:13 UTC by myungjinsim

## 작업 내용

- Ranking/RankingView 
- Component/RankingList 

![Ranking](https://user-images.githubusercontent.com/75699831/213207713-5d0b4746-a809-4452-95bb-e8370e46b2c0.png)
![Profile](https://user-images.githubusercontent.com/75699831/213207730-ed9de704-8683-4a78-8d1a-1ad39c6a5a28.png)
 [ ] 

## 리뷰 포인트

-

## 질문

- NavigationTitle의 폰트와 색깔을 어떻게 바꾸는 지 모르겠어요 

## 다음 진행할 작업
- 데이터 연결
- MVVM 형식으로 수정 

## 참고한 자료

- https://seons-dev.tistory.com/entry/SwiftUI-List

2023-01-18 15:50 UTC, otoolz approved these changes
굿굿입니다!

2023-01-18 15:50 UTC, otoolz commented on GBZG/View/Ranking/RankingView.swift
> +                .listRowSeparator(.hidden)
역시 스유는 엄청나군요

2023-01-18 15:50 UTC, otoolz commented on GBZG/View/Ranking/RankingView.swift
> +
https://github.com/GBZG/GBZG/wiki/code-convention#%EB%B9%88-%EC%A4%84
저희 공백 라인에 대한 코드 컨벤션입니당 :)

2023-01-18 16:18 UTC, myungjinsim commented on GBZG/View/Ranking/RankingView.swift
> +
역시 컨벤션 대왕님! 감사합니다

2023-01-20 03:43 UTC, DevLuce approved these changes
3억 1천만원 연봉 달성 축하합니다!! :)
고생하셨어용~!

2023-01-21 04:30 UTC, phainestha1 requested changes
🔥
타인의 작업물을 건드린 기록이 있네요. 컨플릭트 날 수 있어서
이 부분은 수정이 필요합니다. 이슈 해결을 위해 Request Change 할게요..!

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Component/RankingList.swift
> +
불필요한 개행은 삭제해주세요.

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Ranking/RankingView.swift
> +
불필요한 개행은 삭제해주세요.

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Component/RankingList.swift
> +struct RankingList: View {
이 컴포넌트는 인생랭킹 목록을 구성하는 각각의 테마 정보들인 것으로 보이는데 이름을 RankingList라고 하면 리스트 전체를 의미하는 것 같습니다.
@otoolz @timo-nam @DevLuce 보다 더 직관적인 명칭이 필요할 것 같습니다.

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Ranking/RankingView.swift
> +
불필요한 개행은 삭제해주세요.

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Ranking/RankingView.swift
> +
불필요한 개행은 삭제해주세요.

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Ranking/RankingView.swift
> +    @Environment(\.presentationMode) private var presentationMode
https://developer.apple.com/documentation/swiftui/presentationmode

deprecated 될 예정입니다.
@Environment(\.dismiss) private var dismiss 사용이 필요합니다.

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Ranking/RankingView.swift
> +
@otoolz @timo-nam @DevLuce 
이 부분 개행이 필요할까요?

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Ranking/RankingView.swift
> +    }
ViewModel로 옮겨주세욤

2023-01-21 04:30 UTC, phainestha1 commented on GBZG/View/Write/WriteView.swift
> +//
타인의 작업물은 수정하지 않아야 합니다.
컨플릭트 날 수 있어욤

2023-01-21 04:33 UTC, phainestha1 reviewed
🔥

2023-01-21 04:33 UTC, phainestha1 commented on GBZG/View/Ranking/RankingView.swift
> +        NavigationView{
private extension으로 뷰 컴포넌트를 관리하는 것이 차후 유지-보수에 있어 용이하답니답
https://github.com/GBZG/GBZG/blob/dev/GBZG/View/Write/WriteView.swift

2023-01-21 05:36 UTC, phainestha1 commented
@otoolz 
PR 제목 컨벤션 준수 필요합니다. 👀

2023-01-21 05:46 UTC, DevLuce commented on GBZG/View/Component/RankingList.swift
> +struct RankingList: View {
UIKit에서는 Cell로 통용하고 SwiftUI 에서는 Row 또는 Item 이라는 네이밍을 주로 쓰는 것 같습니당

2023-01-21 05:47 UTC, DevLuce commented on GBZG/View/Ranking/RankingView.swift
> +
아래 변수들과 성격이 다르다면 개행이 있는게 가독성에서 괜찮지 않을까요?

2023-01-27 15:07 UTC, closed without merging