SearchView UI, 검색 로직 완성
GBZG/GBZG pull request #17
Opened 2023-01-24 03:45 UTC by timo-nam

## 작업 내용

<img width="200" alt="image" src="https://user-images.githubusercontent.com/76807762/214207454-96e0ee70-f0cd-481f-bd48-4f2a6ec6c520.png"><img width="200" alt="image" src="https://user-images.githubusercontent.com/76807762/214207617-adaf67eb-b7dd-41a6-8897-1abce0127682.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/76807762/214207731-d7310dac-723a-464b-97d9-dfd936d8fa56.png">

- UI 구현
   - 최근검색기록이 있는 경우
   - 최근검색기록이 없는 경우
   - 검색어가 있는 경우

- 검색 등 로직 추가

- Search 유저스토리 안에서 뷰간 연결

## 리뷰 포인트

- https://github.com/GBZG/GBZG/pull/13
- 이전 PR에서 논의했던 내용들 전부 반영했습니다.

2023-01-24 04:53 UTC, phainestha1 reviewed
🔥

2023-01-24 04:53 UTC, phainestha1 commented on GBZG/View/Write/Search/ThemeRow.swift
> +    }
첫글자를 소문자로 바꾸는 것이 컨벤션 준수에 적합할듯 싶어요~!

2023-01-24 04:53 UTC, phainestha1 commented on GBZG/View/Write/Search/SearchView.swift
> +            SearchResultList(searchKeyword: $searchKeyword)
@otoolz @DevLuce @myungjinsim 
파라미터가 하나인 경우에는 init을 통해서 아래와 같이 파라미터명을 생략하는 것이 어떨까요?
```swift
init(_ text: String) { }
```

2023-01-24 04:53 UTC, phainestha1 commented on GBZG/View/Write/Search/SearchResultList.swift
> +    }
첫글자를 소문자로 바꾸는 것이 컨벤션 준수에 적합할듯 싶어요~!

2023-01-24 04:54 UTC, mxnxxii reviewed
안녕하세요 선생님 다름이 아니라 양옆의 마진은 혹시 언제쯤 추가되는건가 싶어서 질문드리러 왔습니다 🙏🏻

2023-01-24 05:00 UTC, phainestha1 commented
> 안녕하세요 선생님 다름이 아니라 양옆의 마진은 혹시 언제쯤 추가되는건가 싶어서 질문드리러 왔습니다 🙏🏻

양옆치킨

2023-01-24 05:00 UTC, phainestha1 commented
오우 죄송 실수로 닫았네요

2023-01-24 09:29 UTC, DevLuce requested changes
고생하셨어용! 변수명 수정이 필요할 거 같아요 :)

2023-01-24 09:29 UTC, DevLuce commented on GBZG/View/Write/Search/SearchResultList.swift
> +    }
변수와 메소드는 소문자 camelCase!!
클래스와 구조체는 대문자 CamelCase 입니당~

2023-01-24 09:29 UTC, DevLuce commented on GBZG/View/Write/Search/SearchView.swift
> +            SearchResultList(searchKeyword: $searchKeyword)
Swift에서 struct는 지정생성자를 작성하지 않아도 자동으로 내부에서 생성해주는데 전달인자 레이블 생략을 위해 굳이 작성해야할 필요가 있을까용??
이것도 같이 얘기해서 컨벤션을 맞춰보면 좋을거 같아요!!
@timo-nam @otoolz

2023-01-24 09:29 UTC, DevLuce commented on GBZG/View/Write/Search/ThemeRow.swift
> +}
```suggestion
struct TmpThemeRowModel: Identifiable {
    let id = UUID()
    let title: String
    let location: String
}
```

이렇게 줄여볼수도 있을거 같아요!

2023-01-24 17:02 UTC, timo-nam commented on GBZG/View/Write/Search/ThemeRow.swift
> +    }
ㅇㅋㅇㅋ에요

2023-01-24 17:05 UTC, timo-nam commented on GBZG/View/Write/Search/SearchView.swift
> +            SearchResultList(searchKeyword: $searchKeyword)
@DevLuce 혀키 의견에도 동의하는데
인자 이름을 생략해도 누구나 용례를 아는 경우 아니면
이름을 명시적으로 적는 게 좋은 거 같아요

2023-01-24 17:06 UTC, timo-nam commented on GBZG/View/Write/Search/SearchResultList.swift
> +    }
사실 저도 고민했는데 거의 View의 개념으로 쓰는 함수라 대문자로 해봤어요 ㅋㅋㅋ

2023-01-24 17:06 UTC, rafiki-nam commented
> 안녕하세요 선생님 다름이 아니라 양옆의 마진은 혹시 언제쯤 추가되는건가 싶어서 질문드리러 왔습니다 🙏🏻

그건 더 상위뷰에서..

2023-01-24 17:14 UTC, timo-nam commented on GBZG/View/Write/Search/ThemeRow.swift
> +    }
수정했어요~

2023-01-24 17:15 UTC, timo-nam commented on GBZG/View/Write/Search/SearchResultList.swift
> +    }
수정했어요

2023-01-24 17:21 UTC, timo-nam commented on GBZG/View/Write/Search/ThemeRow.swift
> +}
그러면 `let tmpList: [TmpThemeRowModel]`을 정의할 때 수정이 필요해요.
삭제될 부분이니까 일단은 그대로 갑시다..

2023-01-25 13:04 UTC, DevLuce approved these changes
굳! 고생했어용~

2023-01-25 15:01 UTC, phainestha1 approved these changes

2023-01-25 15:02 UTC, merged