[feat] TabView 추가
GBZG/GBZG pull request #3
Opened 2022-11-14 16:06 UTC by otoolz

TabView UI를 추가합니다.

## 작업 내용

- 
<img src = "https://user-images.githubusercontent.com/91725382/201707146-66320f25-04dc-4862-be3c-ae8b309ba239.png" width = 250>

## 리뷰 포인트

- 딱히 없슴다

## 다음 진행할 작업
- 컴퍼넌트 버튼 작업

## 참고한 자료
- https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/tree/develop/HappyAnding/HappyAnding/Views/TabView

2022-11-14 18:24 UTC, phainestha1 commented
본문 내용 무슨 말인지 모르겠습니다.

2022-11-14 18:34 UTC, phainestha1 commented on GBZG/View/GBZGTabView.swift
> +}
시뮬레이터를 자주 사용했으면 좋겠습니다.
이에 프리뷰를 주석 처리 하거나 삭제하는 것은 어떨까요?

2022-11-14 18:34 UTC, phainestha1 commented on GBZG/View/TabRouter.swift
> +    case templete
template 스펠링 확인 부탁드립니다.

2022-11-14 18:34 UTC, phainestha1 commented on GBZG/View/TempleteView.swift
> +//  TempleteView.swift
스펠링 확인 부탁드립니다.

2022-11-14 18:47 UTC, phainestha1 requested changes

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/TabRouter.swift
> +//  TabRouter.swift
enum 명칭과 상이하니 확인 부탁드립니다.
이 파일은 실제 UI를 표시하는 파일이 아니니 Model 쪽에 배치하셔도 될 것 같습니다.

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/TempleteView.swift
> +}
```suggestion
```
👀

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/WriteView.swift
> +}
```suggestion
```
👀

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/TabRouter.swift
> +        case .templete: TempleteView()
👀

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/TabRouter.swift
> +        case .templete: return "person.crop.circle.fill"
👀

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/TabRouter.swift
> +        case .templete: return "Templete"
👀

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/HomeView.swift
> +}
```suggestion
```
👀

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/TabRouter.swift
> +        case .templete: return "Templete"
탭 버튼 상에 명칭이 영어로 표시되네요.
@mxnxxii @myungjinsim 피그마 디자인에는 아이콘만 표시하고 있어 상이합니다.
국영문 표기 확정 부탁드립니다.

2022-11-14 18:47 UTC, phainestha1 commented on GBZG/View/TabRouter.swift
> +    // TODO: 추후에 선정 아이콘에 맞는 이미지나 시스템이미지로 변경
지금 에셋 이미지로는 적용이 불가능할까요?

2022-11-15 01:27 UTC, otoolz commented on GBZG/View/GBZGTabView.swift
> +}
프리뷰 사용하면 간단한 UI 변경사항 빠르게 확인할 수 있어서 유용한 것 같던데, 혹시 이유가 있을까요??

2022-11-15 01:27 UTC, otoolz commented on GBZG/View/TabRouter.swift
> +    case templete
넵, 수정하겠습니다!

2022-11-15 01:32 UTC, otoolz commented on GBZG/View/TabRouter.swift
> +//  TabRouter.swift
넵 Model폴더로 옮겨두겠습니다.
상이하다는게 TabRouter에서 GBZGTabRouter로 변경했으면 좋겠다고 이해했는데 맞나요??

2022-11-15 01:37 UTC, otoolz commented on GBZG/View/TabRouter.swift
> +        case .templete: return "Templete"
넵 제가 에셋에 아이콘이미지가 있는지 확인을 못해서 임의대로 넣어둔 탭아이템라벨이었습니다.
에셋 데이터 확인했고, 수정하겠습니다~

2022-11-15 02:31 UTC, otoolz commented
PR 리뷰 관련 추가 작업 내용
- templete 오타 수정
- TabRouter 이름 변경 -> GBZGTabRouter
- 탭아이템 이미지로 변경 (*아이콘 이미지 더 추가해서 변경 필요)
- 프리뷰 주석처리


* 선택된 탭아이콘은 점점점아이콘으로 변경되며, 추후에 활성화된 탭바 이미지(아마도 색상이 바뀐 현재 아이콘)로 변경예정
에셋데이터에서는 회색이미진데 왜 검정색으로 나오는지는 모르겠어요

https://user-images.githubusercontent.com/91725382/201811818-3c790dc2-ac47-47b5-8f56-8baf29234916.mp4

2022-11-15 02:56 UTC, phainestha1 commented on GBZG/View/GBZGTabView.swift
> +}
저의 경우에는 몇 가지 이유가 있는데,
먼저 실제 뷰를 작성하게 되면 struct 하단에 extension을 통해서 뷰 컴포넌트를 배치하게 되는데 프리뷰 코드가 있는 것이 가독성을 저하시키더라고요.
그리고 프리뷰 코드가 있는 것이 결국은 메모리 관리 측면에서 좋지 않다는 얘기를 들어서 PR 시에는 프리뷰를 주석 처리 하거나 삭제해서 올리는 편입니다. 프리뷰의 경우 mock data를 입력해서 보게 될텐데 굉장히 단편적인 부분만 보게되어서 실제 사용자의 관점에서 보게 될 화면과 완벽하게 일치하지 않는다는 의견입니다유 🫠

2022-11-15 02:58 UTC, phainestha1 commented on GBZG/View/TabRouter.swift
> +//  TabRouter.swift
ㅋㅋㅋ 그러면 재미는 있을듯요
선언된 enum 이름이 Tab 이어서 파일명도 동일해야 하지 않을까라고 생각했습니다.

2022-11-15 04:15 UTC, phainestha1 approved these changes
코멘트 모두 반영되어 어프루브 진행하겠습니다.

2022-11-15 14:20 UTC, mxnxxii commented on GBZG/View/GBZGTabView.swift
> +            }
TabBar Background 컬러가 들어가는것으로 알고 있는데, 적용이 안된 것 같네요!! 확인 한번 부탁드릴게요 :)

2022-11-15 14:26 UTC, DevLuce approved these changes
고생하셨습니다!! 👍

2022-11-15 14:26 UTC, DevLuce commented on GBZG/Model/GBZGTabRouter.swift
> +        case .template: return "Template"
콜론들의 스페이싱에 통일성이 없습니다. 통일성있게 코드 작성 부탁드려요~ (찡긋)

2022-11-15 14:26 UTC, DevLuce commented on GBZG/Model/GBZGTabRouter.swift
> +        }
👀 콜론 스페이싱 통일성! 마찬가지입니당 :)

2022-11-15 14:26 UTC, DevLuce commented on GBZG/View/GBZGTabView.swift
> +//}
프리뷰를 주석처리한 이유가 있을까요?

2022-11-16 00:47 UTC, otoolz commented on GBZG/View/GBZGTabView.swift
> +//}
테오의 의견을 반영하였습니다!

아래 첨부합니다.

> 저의 경우에는 몇 가지 이유가 있는데,
먼저 실제 뷰를 작성하게 되면 struct 하단에 extension을 통해서 뷰 컴포넌트를 배치하게 되는데 프리뷰 코드가 있는 것이 가독성을 저하시키더라고요.
그리고 프리뷰 코드가 있는 것이 결국은 메모리 관리 측면에서 좋지 않다는 얘기를 들어서 PR 시에는 프리뷰를 주석 처리 하거나 삭제해서 올리는 편입니다. 프리뷰의 경우 mock data를 입력해서 보게 될텐데 굉장히 단편적인 부분만 보게되어서 실제 사용자의 관점에서 보게 될 화면과 완벽하게 일치하지 않는다는 의견입니다유 🫠

2022-11-16 01:01 UTC, otoolz commented on GBZG/View/GBZGTabView.swift
> +            }
예 컬러 익스텐션 추가되면 반영하겠습니다!
그런데 색상이 피그마 #HIFI상에는 F9F9F9로 나와있고, 디자인 시스템 상에는 #FCFCFD로 나와있는데 디자인 시스템의 컬러가 맞는거겠죠?

2022-11-16 01:17 UTC, phainestha1 commented on GBZG/Model/GBZGTabRouter.swift
> +        case .template: return "Template"
[f52879e](https://github.com/GBZG/GBZG/pull/3/commits/f52879efe184f3f65078e226bdb0dacb8311347f) 반영되었습니다.

2022-11-16 01:19 UTC, phainestha1 commented on GBZG/View/GBZGTabView.swift
> +            }
컬러 논의는 확정해야 할 내용이 있어서 새로운 PR을 통해 진행하는 것은 어떨까요?
이 PR에서는 기본 UI의 형태만 고려하는 것이 효율적일 것으로 생각됩니다.

2022-11-16 01:20 UTC, phainestha1 commented
컬러 관련 논의는 제가 새로운 PR을 만들어서 내용 전달드릴 수 있도록 하겠습니다 여러분..!
한 PR에 여러 주제를 다루기도 힘들고 이미 코멘트가 많아져서 알아보기가 힘들군요 👀

2022-11-16 01:20 UTC, merged